[features]
seeds = true

[programs.devnet]
event_manager_program = "FYMHu78S37EpfuBFcQ6XyCqaQLhtTqkVxZbuKm8CY6A6"

[programs.localnet]
event_manager_program = "FYMHu78S37EpfuBFcQ6XyCqaQLhtTqkVxZbuKm8CY6A6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/disco-protocol.json" # 98fkfqYjkDumBRwjZQxeaQo89rprxonHDDk6yXZBSJiK

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.spec.ts"
